spring:
  redis:
    host: 172.16.7.235
    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.7.235:8066/ZFCG?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 1800000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  rabbitmq:
    host: 172.16.7.235
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
  mvc:
    servlet:
      load-on-startup: 1
mybatis:
  mapperLocations: classpath*:mapper/**Mapper.xml
  typeAliasesPackage: com.gpm
  configuration:
    mapUnderscoreToCamelCase: true
access_token:
  store-jwt: false
  jwt-signing-key: jiang@su@cai@gou=$==+_+%0%:)(:)
  add-userinfo: false
logging:
  level:
    root: info
    com.gpm: debug
    com.alibaba.druid: error
    org.springframework.web: error
  path: ${user.home}/tomcat/fins-apps/gpm-server/${spring.application.name}/logs/
#打开feign-hystrix
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enable: true
ribbon:
  eager-load:
    enabled: true
    clients: cloud-system
  ReadTimeout: 30000
  ConnectTimeout: 30000
  #OkToRetryOnAllOperations: true
  #MaxAutoRetries: 1
  #MaxAutoRetriesNextServer: 1
verify:
  image:
    savePath: ${user.home}/tomcat/fins-apps/gpm-server/${spring.application.name}/verifyImage/


